[RecentFiles]
File1[$e]=/run/media/steinardth/Hardur_Diskur/.torrent/Smiling.Friends.S02.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViETNAM/Smiling.Friends.S02E01.Gwimbly.Definitive.Remastered.Enhanced.Extended.Edition.DX.4k.Anniversary.Directors.Cut.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViETNAM.mkv
File2[$e]=/run/media/steinardth/Hardur_Diskur/.torrent/Mad.God.2021.1080p.WEB.H264-NAISU[rarbg]/mad.god.2021.1080p.web.h264-naisu.mkv
File3[$e]=$HOME/Downloads/.torrent/Tom and Jerry Cartoons Complete Collection (1940-2007) [DVDRip] M8/001   Puss Gets the Boot [1940].avi
Name1[$e]=Smiling.Friends.S02E01.Gwimbly.Definitive.Remastered.Enhanced.Extended.Edition.DX.4k.Anniversary.Directors.Cut.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViETNAM.mkv
Name2[$e]=mad.god.2021.1080p.web.h264-naisu.mkv
Name3[$e]=001   Puss Gets the Boot [1940].avi
