[RecentFiles]
File1[$e]=/mnt/PlexMedia/Star Wars/TV Shows/Star Wars: Tales of the Jedi & Empire/Star.Wars.Tales.of.the.Jedi.The.One.Who.Fell.From.the.Light.x265.1080p-NumeralJ.mkv
File2[$e]=/mnt/PlexMedia/Star Wars/TV Shows/Star Wars: Tales of the Jedi & Empire/Star.Wars.Tales.of.the.Jedi.The.One.Who.Faces.the.Dark.x265.1080p-NumeralJ.mkv
File3[$e]=/mnt/PlexMedia/Star Wars/TV Shows/Star Wars The Clone Wars The TV Film Cuts COMPLETE SERIES/Star Wars The Clone Wars - The Crystal Crisis Film Cut (Bonus).mp4
File4[$e]=/run/media/steinardth/Hardur_Diskur/.torrent/Squid Game - Season 2/Squid Game - S02E01 - Bread and Lottery.mkv
File5[$e]=/run/media/steinardth/Hardur_Diskur/Recording/Squad - 2025-01-06 21-54-53.mp4
Name1[$e]=Star.Wars.Tales.of.the.Jedi.The.One.Who.Fell.From.the.Light.x265.1080p-NumeralJ.mkv
Name2[$e]=Star.Wars.Tales.of.the.Jedi.The.One.Who.Faces.the.Dark.x265.1080p-NumeralJ.mkv
Name3[$e]=Star Wars The Clone Wars - The Crystal Crisis Film Cut (Bonus).mp4
Name4[$e]=Squid Game - S02E01 - Bread and Lottery.mkv
Name5[$e]=Squad - 2025-01-06 21-54-53.mp4
