[[gamescope-plus]]
url = "https://github.com/Joshua-Ashton/reshade.git"
commit = "4245743a8c41abbe3dc73980c1810fe449359bf1"

[[gamescope-plus]]
url = "https://github.com/Joshua-Ashton/wlroots.git"
commit = "2edf468aeb7d4703aa211cea3b58f04cbc73298c"

[[gamescope-plus]]
url = "https://github.com/KhronosGroup/SPIRV-Headers.git"
commit = "996c728cf7dcfb29845cfa15222822318f047810"

[[gamescope-plus]]
url = "https://github.com/ValveSoftware/openvr.git"
commit = "ae46a8dd0172580648c8922658a100439115d3eb"

[[gamescope-plus]]
url = "https://gitlab.freedesktop.org/emersion/libdisplay-info.git"
commit = "211fa636a3c49da81bcedc115457a003f28f9a58"

[[gamescope-plus]]
url = "https://gitlab.freedesktop.org/emersion/libliftoff.git"
commit = "07fbf143325ac1afcd4af9f9e286c1389a015418"

[[monocoque-git]]
url = "https://github.com/spacefreak18/monocoque"
commit = "12509e9709871afcb3ae264823b4a7d3c3b71bf7"

[[protopedal-git]]
url = "https://gitlab.com/openirseny/protopedal"
commit = "8d0b68f54025f4fc3e39da71f657d8adfc6f4476"

[[universal-pidff-dkms-git]]
url = "https://github.com/JacKeTUs/universal-pidff"
commit = "d95b73e042b0cbd7053adca0324240fd0210c7da"
