# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "uas" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/87d8e1e1-6429-4a67-9e8b-7a976377cf9a";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-1fdb55fe-c3f8-47c3-a865-d2d6a2ab455c".device = "/dev/disk/by-uuid/1fdb55fe-c3f8-47c3-a865-d2d6a2ab455c";
  boot.initrd.luks.devices."luks-736a89e4-a8d5-4c59-9373-79b27f322caf".device = "/dev/disk/by-uuid/736a89e4-a8d5-4c59-9373-79b27f322caf";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D6B1-10B7";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/61f296a5-e3c3-4dd0-bac9-a6a1155d64e7";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
