# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "uas" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4E0A-9495";
    fsType = "vfat";
  };

  boot.initrd.luks.devices."luks-3ca7218a-2f4e-4c54-9951-4e4e98b74be7".device = "/dev/disk/by-uuid/3ca7218a-2f4e-4c54-9951-4e4e98b74be7";
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5b17be92-6e34-4376-a483-27eb1a0a233f";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-d0dc3f4a-c434-49a0-b3f4-0f3d8bba0c1c".device = "/dev/disk/by-uuid/d0dc3f4a-c434-49a0-b3f4-0f3d8bba0c1c";
  swapDevices = [
    {device = "/dev/disk/by-uuid/5aee75fc-f3e5-4a40-8e0e-8e92eee7fc3c";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
