[Audio]
Volume=100

[General]
LastPlayedFile=file:///mnt/PlexMedia/Star Wars/TV Shows/Star Wars: Tales of the Jedi & Empire/Star.Wars.Tales.of.the.Jedi.The.One.Who.Fell.From.the.Light.x265.1080p-NumeralJ.mkv
ShowPreviewThumbnail=true

[Mouse]
Right=openContextMenuAction

[Playback]
MinDurationToSavePosition=2
PauseWhileMinimized=true
SeekToLastPosition=true

[Playlist]
RememberState=true
Visible=true

[Subtitles]
SubtitlesFolders=subs,.
