[Audio]
Volume=100

[General]
LastPlayedFile=file:///run/media/steinardth/SSD_M2/SteamLibrary/steamapps/compatdata/805550/pfx/drive_c/users/steamuser/AppData/Local/CrewChiefV4/Sounds/personalisations/Steinar/prefixes_and_suffixes/well_done/22.wav
ShowPreviewThumbnail=true

[Mouse]
Right=openContextMenuAction

[Playback]
MinDurationToSavePosition=2
PauseWhileMinimized=true
SeekToLastPosition=true

[Playlist]
RememberState=true

[Subtitles]
SubtitlesFolders=subs,.
