[Audio]
Volume=100

[General]
LastPlayedFile=file:///home/steinardth/Downloads/Right ear the Bible (Сhinese), Left ear Mozart (2x speed) ADVANCED.mp4
ShowPreviewThumbnail=true

[Mouse]
Right=openContextMenuAction

[Playback]
MinDurationToSavePosition=2
PauseWhileMinimized=true
SeekToLastPosition=true

[Playlist]
RememberState=true

[Subtitles]
SubtitlesFolders=subs,.
